type: group

fields:
  page_headline:
    type: headline
    numbered: true
    label:
      en: Info
      de: Info

  page_description:
    type: textarea
    buttons: false
    uploads: false
    size: small
    label:
      en: Description
      de: Beschreibung
