title: Standard

fields:
  title:
    type:  text
    label:
      de: Title
      en: Title

  text:
    type:  textarea
    label:
      de: Text
      en: Text

options:
  changeSlug: true
  changeStatus: true
  changeTitle: true
  delete: true
  duplicate: true
  preview: true
  update: true
