title: Standard

options:
  changeSlug: true
  changeStatus: true
  changeTitle: true
  delete: true
  duplicate: true
  preview: true
  update: true

fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
