module.exports = {
  urls: {
    local: 'http://firma.local.blee.ch/',
    live: 'http://www.schramm-reinigung.de/',
  },
  paths: {
    src: {
      config: 'app/site/config/',
      site: 'app/site/',
      languages: 'app/site/languages/',
      fonts: 'app/base/assets/fonts/',
      icons: 'app/base/assets/icons/',
      img: 'app/base/assets/images/',
      favicons: 'app/base/assets/favicons/',
      controllers: 'app/controllers/',
      collections: 'app/collections/',
      blueprints: 'app/blueprints/',
      templates: 'app/templates/',
      snippets: 'app/snippets/',
      scripts: 'app/base/',
      styles: 'app/base/',
    },
    dist: {
      vendor: 'app/dist/base/vendor/',
      config: 'app/dist/site/config/',
      site: 'app/dist/site/',
      languages: 'app/dist/site/languages/',
      fonts: 'app/dist/base/assets/fonts/',
      icons: 'app/dist/base/assets/icons/',
      img: 'app/dist/base/assets/images/',
      favicons: 'app/dist/base/assets/favicons/',
      controllers: 'app/dist/controllers/',
      collections: 'app/dist/collections/',
      blueprints: 'app/dist/blueprints/',
      templates: 'app/dist/templates/',
      snippets: 'app/dist/snippets/',
      scripts: 'app/dist/base/',
      styles: 'app/dist/base/',
    },
    content: [
      'app/access/content/',
    ],
    vendor: [
      'node_modules/jquery/dist/jquery.min.{js,map}',
    ],
  },
}
