type: fields

fields:
    settings_site_headline:
        type: headline
        numbered: true

        label:
            en: Meta Information
            de: Meta Information

    settings_site: fields/settings/page
