type: fields

fields:
    settings_site_headline:
        type: headline
        numbered: true

        label:
            en: Meta Information
            de: Meta Information

    settings_site: fields/settings/site

    settings_site_privacy_headline:
        type: headline
        numbered: true

        label:
            en: Privacy
            de: Privatsphäre

    settings_site_privacy: fields/settings/privacy
