type: group

fields:
  site_description:
    type: textarea
    buttons: false
    uploads: false
    size: small
    label:
      en: Description
      de: Beschreibung

  site_author:
    type: text
    label:
      en: Author
      de: Verfasser

  site_keywords:
    type: tags
    label:
      en: Keywords
      de: Schlagworte
